# Default values for mirror-maker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
env: staging
destination_cluster: ""
source_cluster: ""

image:
  repository: naturalett/mirror-maker
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1"


envVars:
  all:
    KAFKA_HEAP_OPTS: "-Xms512M -Xmx4096M"
    KAFKA_OPTS: -javaagent:/opt/kafka/libs/jmx_prometheus_javaagent-0.19.0.jar=5556:/etc/jmx-kafka-connect/jmx-kafka-connect-prometheus.yml
  staging:
    stg-ue2:
      bootstrap: "<BROKER stg-ue2 1:9098>,<BROKER stg-ue2 2:9098>,<BROKER stg-ue2 3:9098>"
imagePullSecrets:
  - name: ""
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8083

jmx:
  port: 5556

ingress:
  enabled: true
  className: "nginx-int-alb"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: "0.1"
    memory: "3Gi"
  limits:
    cpu: "2"
    memory: "6Gi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector:
  kops.k8s.io/instancegroup: "mirror-maker"

tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Equal
  value: mirror-maker
