version: latest
shortenv: staging
nameOverride: mirror-maker
targetPort: 8083
replicas: 1

envVars:
  all:
    KAFKA_OPTS: -javaagent:/opt/kafka/libs/jmx_prometheus_javaagent-0.19.0.jar=5556:/etc/jmx-kafka-connect/jmx-kafka-connect-prometheus.yml
  staging:
    KAFKA_HEAP_OPTS: "-Xms512M -Xmx4096M"

mirror-maker:
  ingress:
    enabled: false
  resources:
    requests:
      cpu: "1"
      memory: "2.5Gi"
    limits:
      cpu: "2"
      memory: "6Gi"

serviceType: "ClusterIP"
